#没有@DS	主库
#@DS("one")	存在slave指定slave，不存在则主库
#@DS	根据DynamicDataSourceStrategy策略，选择一个从库。默认负载均衡策略。
spring:
  datasource:
    dynamic:
      master:
        username: ${PLAY_READONLY_JDBC_USERNAME}
        password: ${PLAY_READONLY_JDBC_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.0.207:3306/lamp20170928?autoReconnect=true&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC
        type: com.alibaba.druid.pool.DruidDataSource
      slave:
        one:
          username: ${PLAY_READONLY_JDBC_USERNAME}
          password: ${PLAY_READONLY_JDBC_PASSWORD}
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.0.207:3306/lamp20170928?autoReconnect=true&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC
          type: com.alibaba.druid.pool.DruidDataSource
        two:
          username: ${PLAY_READONLY_JDBC_USERNAME}
          password: ${PLAY_READONLY_JDBC_PASSWORD}
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.0.207:3306/eds_channel?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
          type: com.alibaba.druid.pool.DruidDataSource