
server:
  port: 8080
  #tomcat
  tomcat:
    uri-encoding: utf-8
    max-threads: 1000
    min-spare-threads: 30
  connection-timeout: 5000ms

#@DS("slave") 选择从库
spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        master:
          username: ${PLAY_READONLY_JDBC_USERNAME}
          password: ${PLAY_READONLY_JDBC_PASSWORD}
          driver-class-name: com.mysql.cj.jdbc.Driver
          url:
          type: com.alibaba.druid.pool.DruidDataSource
        slave:
          username: ${PLAY_READONLY_JDBC_USERNAME}
          password: ${PLAY_READONLY_JDBC_PASSWORD}
          driver-class-name: com.mysql.cj.jdbc.Driver
          url:
          type: com.alibaba.druid.pool.DruidDataSource

##刷新mapper 调试神器
mybatis-plus:
  global-config:
    refresh-mapper: true

#其他
dc:
  filePath: /Users/didi/Temp/dcFile/
  fileUrlPath: /dcFile/