# 所有环境通用的配置，放在这里
spring:
  profiles:
    # 环境 dev|pre|pro
    active: dev

# Mybatis配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  #typeAliasesPackage: com.eds.tv.entity

logging:
  path: C:/Users/root/Desktop/eds/TV/log
  file: my.log
  level:
    org.springframework.web: error



